# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT clouddex.wsgi

beta_settings:
    cloud_sql_instances: pokemonteambuilder-163623:us-central1:teambuilder

runtime_config:
  python_version: 3
# [END runtime]