# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teambuilder', '0002_auto_20170403_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='fname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(default='lname', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
