# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teambuilder', '0004_auto_20170404_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('action_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeambuilderItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'teambuilder_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeambuilderMove',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('pors', models.BooleanField()),
                ('type', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('description', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'teambuilder_move',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeambuilderPokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pnum', models.IntegerField()),
                ('pname', models.CharField(max_length=50)),
                ('primarytype', models.CharField(max_length=50)),
                ('secondarytype', models.CharField(max_length=50)),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('spattack', models.IntegerField()),
                ('spdefense', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
            options={
                'db_table': 'teambuilder_pokemon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeambuilderTeam',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('teamname', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'teambuilder_team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeambuilderTeammember',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('teamid', models.IntegerField()),
                ('position', models.IntegerField()),
                ('pname', models.CharField(max_length=50)),
                ('pability', models.CharField(max_length=50)),
                ('pitem', models.CharField(max_length=50)),
                ('movea', models.CharField(max_length=50)),
                ('moveb', models.CharField(max_length=50)),
                ('movec', models.CharField(max_length=50)),
                ('moved', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'teambuilder_teammember',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeambuilderUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('userid', models.IntegerField()),
            ],
            options={
                'db_table': 'teambuilder_user',
                'managed': False,
            },
        ),
    ]
