# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teambuilder', '0014_auto_20170405_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='team',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
